name: Docker CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t print-demo .

      - name: Run Docker container
        run: |
          mkdir -p logs
          docker run --rm -v "$(pwd)/logs:/home/logs/" print-demo

      - name: Check logs directory
        run: ls -R logs/

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/
